src/components/Language/LanguageFlyout.css, src/components/Language/LanguageFlyout.js, src/components/Layout/Header.js
=> Redesign LanguageFlyout: Fixed when scrolling

src/endpoints/disclaimer.js, src/endpoints/index.js, src/main.js, src/routes/DisclaimerPage/index.js, src/routes/LocationPage/index.js
=> Webapp 10: Impressum for every location

src/components/Layout/Header.css, src/components/Layout/Header.js, src/components/Layout/HeaderDropDown.js
Set line-height of font-awesome-symbol to match height of header.
=> WEBAPP-39: Fix Header for iOS / Safari

src/components/RichLayout/index.js, src/endpoints/createFetcher.js, src/endpoints/page.js
=> WEBAPP-41: Fix language switching

src/components/RichLayout/Footer.css, src/components/RichLayout/Header.css, src/components/RichLayout/index.js, src/components/RichLayout/style.css
force footer to stay on bottom of page/bottom of viewport depending on which is bigger
adjusted design of the footer, maybe we have to change the color when we get our new color palette
=> WEBAPP-98: adjust the design of the footer

src/components/Layout/style.css
=> WEBAPP-129  Set background-color: white; on body for Sven's Firefox

src/components/Common/Helper.css, src/components/Content/RemoteContent.css, src/components/LanguageFlyout/style.css, src/components/Layout/index.js, src/components/Layout/style.css, src/components/RichLayout/Footer.css, src/components/RichLayout/Header.css, src/components/RichLayout/style.css
=> WEBAPP-96: New Font for arabic-languages + Content with latin letters use Open-Sans + Fonts load on first use

src/modules/layout/components/Footer.css, src/modules/layout/components/Footer.js, src/modules/layout/components/GeneralFooter.js, src/modules/layout/components/LocationFooter.js, src/modules/layout/components/__tests__/__snapshots__/Footer.spec.js.snap, src/modules/layout/components/__tests__/__snapshots__/GeneralFooter.spec.js.snap, src/modules/layout/components/__tests__/__snapshots__/LocationFooter.spec.js.snap
=> WEBAPP-161: Add link to Datenschutzerklärung to footer

src/components/RichLayout/Footer.js
Got no translation, but there's no in develop as well.
=> WEBAPP-187: Add Datenschutz to Footer in master branch

src/modules/endpoint/endpoints/__tests__/events.spec.js, src/modules/endpoint/endpoints/events.js
=> WEBAPP-232: Consider EndDate when filtering events

package.json
=> Bump version to 2018.03.2

src/modules/common/components/Headroom.js
=> WEBAPP-270: Fix position sticky bugfix

src/locales.json, src/modules/common/components/ScrollingSearchBox.js, src/modules/common/components/SearchInput.js, src/modules/common/components/__tests__/ScrollingSearchBox.spec.js, src/modules/common/components/__tests__/SearchInput.spec.js, src/modules/common/components/__tests__/__snapshots__/ScrollingSearchBox.spec.js.snap, src/modules/common/components/__tests__/__snapshots__/SearchInput.spec.js.snap, src/routes/landing/components/FilterableCitySelector.js, src/routes/landing/components/__tests__/FilterableCitySelector.spec.js, src/routes/landing/components/__tests__/__snapshots__/FilterableCitySelector.spec.js.snap, src/routes/landing/containers/__tests__/__snapshots__/LandingPage.spec.js.snap, src/routes/search/containers/SearchPage.js, src/routes/search/containers/__tests__/__snapshots__/SearchPage.spec.js.snap
=> WEBAPP-77: Add label for inputs

package.json, yarn.lock
=> WEBAPP-273: downgrade normalize url

package.json
=> Bump-Version: Change version to 2018.05.0

src/locales.json
=> WEBAPP-133: Add french locale to locales.json

src/routes/categories/components/CategoryList.js, src/routes/categories/components/CategoryListItem.js, src/routes/categories/components/CategoryListItem.styles.js, src/routes/categories/components/__tests__/CategoryListItem.spec.js, src/routes/categories/components/__tests__/__snapshots__/CategoryListItem.spec.js.snap, src/routes/categories/containers/CategoriesPage.js, src/routes/categories/containers/__tests__/__snapshots__/CategoriesPage.spec.js.snap, src/routes/search/containers/SearchPage.js, src/routes/search/containers/__tests__/__snapshots__/SearchPage.spec.js.snap
=> WEBAPP-259: Remove 3rd level category icons

src/modules/endpoint/endpoints/__tests__/events.spec.js, src/modules/endpoint/endpoints/events.js
=> WEBAPP-263: Use events api v3

src/modules/endpoint/endpoints/__tests__/languages.spec.js, src/modules/endpoint/endpoints/languages.js, src/modules/endpoint/models/LanguageModel.js
=> WEBAPP-265: Use api v3 in languages endpoint

package.json
=> Bump version2018.06.0

README.md, src/routes/wohnen/components/__tests__/__snapshots__/OfferListItem.spec.js.snap
Forgot to update snapshot. This fixes the test.
=> WEBAPP-290: Fix tests

tools/deploy/ssh-deploy.sh
=> WEBAPP-319: Fix deploy script

Jenkinsfile, src/modules/app/errors/CityNotFoundError.js, src/modules/app/errors/LanguageNotFoundError.js, src/modules/common/components/__tests__/__snapshots__/FailureSwitcher.spec.js.snap, src/modules/endpoint/__tests__/Endpoint.spec.js, src/modules/endpoint/errors/LoadingError.js, src/modules/endpoint/errors/MappingError.js, src/modules/endpoint/errors/ParamMissingError.js
=> WEBAPP-326: fix error handling

src/locales.json, src/modules/endpoint/FeedbackEndpoint.js, src/routes/categories/containers/CategoriesToolbar.js, src/routes/categories/containers/__tests__/__snapshots__/CategoriesToolbar.spec.js.snap, src/routes/feedback/components/Feedback.js, src/routes/feedback/components/FeedbackBox.js, src/routes/feedback/components/FeedbackModal.js, src/routes/search/components/SearchFeedback.js, src/routes/search/containers/SearchPage.js, src/routes/search/containers/__tests__/SearchPage.spec.js, src/routes/search/containers/__tests__/__snapshots__/SearchPage.spec.js.snap
=> WEBAPP-210: Add feedback to search results

src/modules/i18n/containers/I18nProvider.js, src/modules/i18n/containers/__tests__/__snapshots__/I18nProvider.spec.js.snap
=> WEBAPP-320: Fix language fallback for raumfrei extra

package.json, src/modules/app/containers/__tests__/Switcher.spec.js, src/modules/app/routes/events.js, src/modules/common/errors/ContentNotFoundError.js, src/modules/endpoint/endpoints/events.js, src/modules/endpoint/models/EventModel.js, src/modules/layout/containers/__tests__/LocationLayout.spec.js, src/routes/events/components/__tests__/EventDetail.spec.js, src/routes/events/components/__tests__/EventList.spec.js, src/routes/events/components/__tests__/EventListElement.spec.js, src/routes/events/components/__tests__/__snapshots__/EventDetail.spec.js.snap, src/routes/events/components/__tests__/__snapshots__/EventList.spec.js.snap, src/routes/events/containers/EventsPage.js, src/routes/events/containers/__tests__/EventsPage.spec.js, src/routes/events/containers/__tests__/__snapshots__/EventsPage.spec.js.snap
=> WEBAPP-338: Hot fix display of events

package.json, src/modules/app/containers/__tests__/Switcher.spec.js, src/modules/app/routes/events.js, src/modules/common/errors/ContentNotFoundError.js, src/modules/endpoint/endpoints/events.js, src/modules/endpoint/models/EventModel.js, src/modules/layout/containers/__tests__/LocationLayout.spec.js, src/routes/events/components/__tests__/EventDetail.spec.js, src/routes/events/components/__tests__/EventList.spec.js, src/routes/events/components/__tests__/EventListElement.spec.js, src/routes/events/components/__tests__/__snapshots__/EventDetail.spec.js.snap, src/routes/events/components/__tests__/__snapshots__/EventList.spec.js.snap, src/routes/events/containers/EventsPage.js, src/routes/events/containers/__tests__/EventsPage.spec.js, src/routes/events/containers/__tests__/__snapshots__/EventsPage.spec.js.snap
PR for Hotfix to merge into master-branch
=> HOTFIX: WEBAPP-338: Fix Display of events

Jenkinsfile, package.json, tools/webpack.config.js, yarn.lock
WEBAPP-340: only babel-load query-string in node-modules
=> WEBAPP-340: Proposal3: only babel-load query-string in node-modules

package.json, src/modules/endpoint/endpoints/events.js
Do you have any idea, why this worked before? Why did the test not fail?
=> WEBAPP-342: Fix events in IE

src/modules/app/routes/__tests__/extras.spec.js, src/modules/app/routes/extras.js, src/modules/app/routesMap.js, src/modules/common/components/FailureSwitcher.js, src/modules/common/components/__tests__/__snapshots__/FailureSwitcher.spec.js.snap, src/routes/categories/containers/CategoriesPage.js, src/routes/categories/containers/__tests__/CategoriesPage.spec.js, src/routes/categories/containers/__tests__/__snapshots__/CategoriesPage.spec.js.snap, src/routes/extras/containers/ExtrasPage.js, src/routes/extras/containers/__tests__/ExtrasPage.spec.js, src/routes/extras/containers/__tests__/__snapshots__/ExtrasPage.spec.js.snap
=> WEBAPP-356: Show right error if an extra is not found

package.json, src/polyfills.js, yarn.lock
=> HOTFIX: WEBAPP-357: Fix internal links in ie

package.json, src/polyfills.js, yarn.lock
=> WEBAPP-357: Fix internal links in ie

src/modules/app/__tests_/getLanguageChangePath.spec.js, src/modules/app/getLanguageChangePath.js
=> WEBAPP-362: Fix language change for internal extras

src/modules/endpoint/endpoints/__tests__/events.spec.js, src/modules/endpoint/endpoints/events.js
=> WEBAPP-380: Fix showing of times

src/modules/app/containers/App.js, src/modules/app/containers/__tests__/App.spec.js, src/modules/app/containers/__tests__/__snapshots__/App.spec.js.snap
=> WEBAPP-267: Add StrictMode to App

src/modules/endpoint/EndpointBuilder.js, src/modules/feedback/components/FeedbackBoxContainer.js, src/routes/search/components/NothingFoundFeedbackBox.js, src/routes/search/components/SearchFeedback.js
Forgot to do the changes. Will just merge this as this is basically already reviewed.
=> WEBAPP-393: Changes requested by klinzo

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
=> WEBAPP-411: Update contributation templates

src/__mocks__/react-i18next.js, src/modules/common/components/Failure.js, src/modules/common/components/FailureSwitcher.js, src/modules/common/components/LastUpdateInfo.js, src/modules/common/containers/LanguageFailure.js, src/modules/common/containers/LanguageSelector.js, src/modules/feedback/components/FeedbackBox.js, src/modules/feedback/components/FeedbackBoxContainer.js, src/modules/feedback/components/FeedbackThanksMessage.js, src/modules/feedback/components/FeedbackToolbarItem.js, src/modules/layout/components/GeneralFooter.js, src/modules/layout/components/HeaderLanguageSelectorItem.js, src/modules/layout/components/LocationFooter.js, src/modules/layout/containers/LocationHeader.js, src/routes/categories/containers/CategoriesPage.js, src/routes/categories/containers/CategoriesToolbar.js, src/routes/disclaimer/containers/DisclaimerPage.js, src/routes/events/containers/EventsPage.js, src/routes/extras/containers/ExtrasPage.js, src/routes/landing/components/FilterableCitySelector.js, src/routes/landing/components/Heading.js, src/routes/landing/containers/LandingPage.js, src/routes/pois/containers/PoiPage.js, src/routes/search/components/NothingFoundFeedbackBox.js, src/routes/search/components/SearchFeedback.js, src/routes/search/containers/SearchPage.js, src/routes/sprungbrett/containers/SprungbrettExtraPage.js, src/routes/wohnen/components/OfferDetail.js, src/routes/wohnen/containers/WohnenExtraPage.js
=> WEBAPP-404: Replace translate with withNamespaces

src/modules/common/components/RemoteContent.js, src/modules/common/components/__tests__/__snapshots__/RemoteContent.spec.js.snap, src/routes/events/containers/EventsPage.js
=> WEBAPP-423: Fix internal linking

package.json, www/index.ejs
=> HOTFIX: WEBAPP-425: Fix ie11 pointer events

src/modules/app/route-configs/CategoriesRouteConfig.js, src/modules/app/route-configs/DisclaimerRouteConfig.js, src/modules/app/route-configs/EventsRouteConfig.js, src/modules/app/route-configs/ExtrasRouteConfig.js, src/modules/app/route-configs/I18nRedirectRouteConfig.js, src/modules/app/route-configs/MainDisclaimerRouteConfig.js, src/modules/app/route-configs/PoisRouteConfig.js, src/modules/app/route-configs/RouteConfig.js, src/modules/app/route-configs/SearchRouteConfig.js, src/modules/app/route-configs/SprungbrettRouteConfig.js, src/modules/app/route-configs/WohnenRouteConfig.js, src/modules/app/route-configs/__tests__/CategoriesRouteConfig.spec.js, src/modules/app/route-configs/__tests__/DisclaimerRouteConfig.spec.js, src/modules/app/route-configs/__tests__/EventsRouteConfig.spec.js, src/modules/app/route-configs/__tests__/ExtrasRouteConfig.spec.js, src/modules/app/route-configs/__tests__/I18nRedirectRouteConfig.spec.js, src/modules/app/route-configs/__tests__/LandingRouteConfig.spec.js, src/modules/app/route-configs/__tests__/MainDisclaimerRouteConfig.spec.js, src/modules/app/route-configs/__tests__/NotFoundRouteConfig.spec.js, src/modules/app/route-configs/__tests__/PoisRouteConfig.spec.js, src/modules/app/route-configs/__tests__/SearchRouteConfig.spec.js, src/modules/app/route-configs/__tests__/SprungbrettRouteConfig.spec.js, src/modules/app/route-configs/__tests__/WohnenRouteConfig.spec.js, src/modules/app/route-configs/__tests__/__snapshots__/index.spec.js.snap, src/modules/app/route-configs/__tests__/index.spec.js, src/modules/common/containers/Helmet.js
=> WEBAPP-426: Test route configs

src/modules/app/containers/RouteContentSwitcher.js, src/modules/app/route-configs/RouteConfig.js, src/modules/common/containers/LanguageFailure.js, src/modules/common/containers/LanguageSelector.js, src/modules/common/containers/__tests__/LanguageSelector.spec.js
=> WEBAPP-432: Use right location type

src/locales.json, src/modules/app/errors/CityNotFoundError.js, src/modules/common/components/FailureSwitcher.js, src/modules/common/components/__tests__/__snapshots__/FailureSwitcher.spec.js.snap, src/modules/common/containers/LanguageFailure.js, src/modules/common/containers/__tests__/__snapshots__/LanguageFailure.spec.js.snap
=> WEBAPP-209: Check translation keys

src/modules/app/PayloadDataType.js, src/modules/app/StoreActionType.js, src/modules/app/actions/finishFetchAction.js, src/modules/app/actions/startFetchAction.js, src/modules/app/containers/App.js, src/modules/app/containers/Switcher.js, src/modules/app/containers/__tests__/Switcher.spec.js, src/modules/app/createReduxStore.js, src/modules/app/fetchData.js, src/modules/app/reducers/__tests__/reducers.spec.js, src/modules/app/reducers/index.js, src/modules/i18n/containers/I18nProvider.js, src/routes/events/containers/__tests__/EventsPage.spec.js, src/routes/extras/containers/__tests__/ExtrasPage.spec.js, src/routes/i18nRedirect/containers/I18nRedirectPage.js, src/routes/wohnen/containers/__tests__/WohnenExtraPage.spec.js
=> WEBAPP-400: Fix type of store

src/routes/events/containers/EventsPage.js
=> WEBAPP-458: Cannot load events with Cyrillic characters in title

package.json, src/routes/categories/containers/CategoriesToolbar.js, src/routes/categories/containers/__tests__/__snapshots__/CategoriesToolbar.spec.js.snap
=> WEBAPP-455: Fix pdf in win10 ie

CODEOWNERS
=> Remove Thomas125 from Codeowner

package.json, src/modules/common/components/Selector.js
=> WEBAPP-486: Fix language modal when title too long

src/modules/layout/containers/LocationHeader.js, src/modules/layout/containers/__tests__/__snapshots__/LocationHeader.spec.js.snap, src/routes/extras/containers/ExtrasPage.js, src/routes/extras/containers/__tests__/__snapshots__/ExtrasPage.spec.js.snap
=> WEBAPP-468:  Change extras to angebote

src/routes/events/components/EventListItem.js, src/routes/events/containers/EventsPage.js, src/routes/pois/components/PoiListItem.js, src/routes/pois/containers/PoisPage.js
=> WEBAPP-502: Don't show null

Jenkinsfile, README.md, src/modules/feedback/components/__tests__/FeedbackBoxContainer.spec.js
=> WEBAPP-449: Change web.integreat-app.de to integreat.app

package.json, tools/deploy/sftp-deploy.sh, tools/deploy/ssh-deploy.sh
=> WEBAPP-515: Fix deployment

package.json, src/modules/common/utils/normalize.js, src/modules/common/utils/normalizeSearchString.js, src/routes/categories/components/CategoryListItem.js, src/routes/categories/components/__tests__/CategoryListItem.spec.js, src/routes/categories/components/__tests__/__snapshots__/CategoryList.spec.js.snap, src/routes/categories/components/__tests__/__snapshots__/CategoryListItem.spec.js.snap, src/routes/landing/components/CityEntry.js, src/routes/landing/components/CitySelector.js, src/routes/landing/components/__tests__/CityEntry.spec.js, src/routes/landing/components/__tests__/__snapshots__/CityEntry.spec.js.snap, src/routes/search/containers/SearchPage.js, yarn.lock
=> WEBAPP-522 and WEBAPP-523: Inconsistent search and improved alias search

src/index.ejs, src/modules/common/components/Breadcrumb.js, src/modules/common/components/Breadcrumbs.js, src/modules/common/components/CleanAnchor.js, src/modules/common/components/__tests__/__snapshots__/Breadcrumbs.spec.js.snap, src/modules/feedback/components/FeedbackModal.js, src/modules/feedback/components/__tests__/__snapshots__/FeedbackModal.spec.js.snap, src/modules/layout/components/Header.js, src/modules/layout/components/HeaderNavigationItem.js, src/modules/layout/components/ToolbarItem.js, src/modules/layout/components/__tests__/__snapshots__/Header.spec.js.snap, src/modules/layout/components/__tests__/__snapshots__/HeaderNavigationItem.spec.js.snap, src/modules/layout/components/__tests__/__snapshots__/Layout.spec.js.snap, src/modules/layout/containers/LocationHeader.js, src/modules/layout/containers/LocationLayout.js, src/modules/layout/containers/__tests__/LocationHeader.spec.js, src/modules/layout/containers/__tests__/__snapshots__/LocationHeader.spec.js.snap, src/modules/layout/containers/__tests__/__snapshots__/LocationLayout.spec.js.snap, src/routes/categories/components/CategoryList.js, src/routes/landing/components/Heading.js
=> WEBAPP-480: Check screen readability

src/routes/categories/components/CategoryListItem.js, src/routes/categories/components/__tests__/__snapshots__/CategoryListItem.spec.js.snap
=> WEBAPP-526: Fix grandparents

.babelrc.js, yarn.lock
=> WEBAPP-525: bug fix - compile webapp on windows

src/modules/layout/components/GeneralFooter.js, src/modules/layout/components/LocationFooter.js, src/modules/layout/components/__tests__/__snapshots__/GeneralFooter.spec.js.snap, src/modules/layout/components/__tests__/__snapshots__/LocationFooter.spec.js.snap
=> WEBAPP-467 added about to footer

CODEOWNERS, README.md, docs/02-technology-stack.md, package.json
=> WEBAPP-524: Update readme (again)

src/modules/feedback/components/FeedbackBoxContainer.js, src/modules/feedback/components/__tests__/FeedbackBoxContainer.spec.js, src/modules/feedback/components/__tests__/__snapshots__/FeedbackBoxContainer.spec.js.snap
=> WEBAPP-538: Prevent feedback for dashboard

src/modules/app/containers/RouteContentSwitcher.js
=> Webapp 436 fix infinite loading spinner

locales/locales.json, src/routes/search/containers/SearchPage.js, src/routes/search/containers/__tests__/__snapshots__/SearchPage.spec.js.snap
=> WEBAPP-471: Search placeholder

src/modules/common/components/RemoteContent.js
=> WEBAPP-507: Content wider than screen

src/modules/app/route-configs/CategoriesRouteConfig.js, src/modules/app/route-configs/EventsRouteConfig.js, src/modules/app/route-configs/ExtrasRouteConfig.js, src/modules/app/route-configs/__tests__/EventsRouteConfig.spec.js, src/modules/app/route-configs/__tests__/ExtrasRouteConfig.spec.js, src/routes/events/containers/EventsPage.js, src/routes/events/containers/__tests__/EventsPage.spec.js, src/routes/extras/containers/ExtrasPage.js, src/routes/extras/containers/__tests__/ExtrasPage.spec.js
=> WEBAPP-550: Disable events if flag is not set

src/modules/app/route-configs/ExtrasRouteConfig.js, src/modules/app/route-configs/SprungbrettRouteConfig.js, src/modules/app/route-configs/WohnenRouteConfig.js, src/modules/app/route-configs/__tests__/ExtrasRouteConfig.spec.js, src/modules/app/route-configs/__tests__/SprungbrettRouteConfig.spec.js, src/modules/app/route-configs/__tests__/WohnenRouteConfig.spec.js, src/modules/app/route-configs/__tests__/__snapshots__/index.spec.js.snap, src/modules/common/components/__tests__/__snapshots__/FailureSwitcher.spec.js.snap, src/modules/layout/containers/__tests__/__snapshots__/LocationHeader.spec.js.snap, src/routes/extras/containers/__tests__/__snapshots__/ExtrasPage.spec.js.snap, src/routes/wohnen/components/__tests__/__snapshots__/OfferListItem.spec.js.snap
=> WEBAPP-499: Change route extras to offers

src/routes/categories/components/CategoryListItem.js, src/routes/categories/components/__tests__/__snapshots__/CategoryListItem.spec.js.snap
=> WEBAPP-582: Make category search less obstrusive

src/routes/landing/components/CityEntry.js, src/routes/landing/components/__tests__/__snapshots__/CityEntry.spec.js.snap
=> WEBAPP-576: Make alias search less obstrusive

.circleci/config.yml, build/bump-version
=> WEBAPP-552: Tag releases

src/modules/layout/components/Header.js, src/modules/layout/components/HeaderActionItemDropDown.js, src/modules/layout/components/HeaderLogo.js, src/modules/layout/components/HeaderTitle.js, src/modules/layout/components/Layout.js, src/modules/layout/components/__tests__/__snapshots__/Header.spec.js.snap
=> WEBAPP-588: Fix IE11 glitches

README.md
=> WEBAPP-587: Add link to glossary

package.json, src/modules/common/components/LoadingSpinner.js, yarn.lock
=> WEBAPP-588: Replace bloated loading spinner

README.md, docs/05-browser-stack.md
=> WEBAPP-533: Supported browser

build-configs/configs/BuildConfigType.js, build-configs/configs/integreat/index.js, build-configs/configs/malte/index.js, src/index.ejs, src/modules/layout/components/Header.js, tools/webpack.config.babel.js
=> WEBAPP-603: Use correct appName for Malte

.circleci/config.yml, .circleci/src/jobs/prepare_production_delivery.yml, .gitignore
=> WEBAPP-616: Fix releases

.circleci/config.yml, .circleci/src/jobs/build.yml
=> WEBAPP-617: Pass commit sha

locales/locales.json, src/modules/layout/components/Header.js
=> WEBAPP-618: Fix scrollbar in navigation bar

build-configs/configs/BuildConfigType.js, build-configs/configs/integreat/assets/manifest.json, build-configs/configs/integreat/index.js, src/index.ejs, src/main.js
=> WEBAPP-560: Hide splashscreen for malte

.circleci/config.yml, .circleci/src/@workflows.yml, .circleci/trigger-pipeline, .github/CONTRIBUTING.md, README.md, docs/03-delivery.md, docs/06-cicd.md
=> WEBAPP-630: Migrate to main

.circleci/config.yml, .circleci/src/commands/restore_environment_variables.yml, .circleci/src/jobs/build.yml, .circleci/src/jobs/deliver.yml, .circleci/src/jobs/prepare_production_delivery.yml, package.json, release-notes/ReleaseNoteTemplate.yml, release-notes/unreleased/WEBAPP-627-ParseReleaseNotes.yml, tools/bump-version, tools/constants.js, tools/create-jira-release, tools/move-release-notes, tools/next-version, tools/parse-release-notes, yarn.lock
=> WEBAPP-627: Parse release notes

build-configs/configs/BuildConfigType.js, build-configs/configs/malte/index.js, flow-typed/globals.js, src/.eslintrc, src/main.js, src/modules/app/constants/buildConfig.js, src/modules/app/constants/urls.js, src/modules/common/components/RemoteContent.js, src/modules/i18n/__mocks__/locales.json, src/modules/i18n/__mocks__/malte-locales.json, src/modules/i18n/__tests__/__snapshots__/loadLocales.spec.js.snap, src/modules/i18n/__tests__/loadLocales.spec.js, src/modules/i18n/containers/I18nProvider.js, src/modules/i18n/containers/__tests__/I18nProvider.spec.js, src/modules/i18n/containers/__tests__/__snapshots__/I18nProvider.spec.js.snap, src/modules/i18n/loadLocales.js, src/modules/layout/components/Header.js, src/modules/layout/containers/LocationHeader.js, src/modules/theme/constants/theme.js, src/modules/theme/containers/CustomThemeProvider.js, src/routes/landing/components/Heading.js, src/setupTest.js, tools/webpack.config.babel.js
=> WEBAPP-586: Locale override

src/routes/sprungbrett/containers/SprungbrettOfferPage.js, src/routes/sprungbrett/containers/__tests__/__snapshots__/SprungbrettOfferPage.spec.js.snap
=> WEBAPP-303: Add logo for sprungbrett-into-work

src/routes/categories/components/CategoryEntry.js, src/routes/categories/components/__tests__/CategoryEntry.spec.js
=> WEBAPP-643: Fix display sub categories

.circleci/config.yml, .circleci/src/jobs/prepare_production_delivery.yml, tools/parse-release-notes
=> WEBAPP-641: Use english release notes for github

tools/webpack.config.babel.js
=> WEBAPP-644: EventJsonLd timezone is wrong

release-notes/unreleased/WEBAPP-651-FixUmlautsInContentSearch.yml, src/routes/categories/components/ContentMatcher.js
=> WEBAPP-651: Fixed searching for Umlauts

tools/create-jira-release
=> WEBAPP-650: Fix jira path
